server:
  port: 8080
  servlet:
    context-path: /agri-machinery

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/agricultural_machinery_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

# MyBatis-Plus配置
mybatis-plus:
  # mapper.xml文件位置
  mapper-locations: classpath*:mapper/**/*.xml
  # 实体类包路径
  type-aliases-package: org.agrimachinerymanager.entity
  configuration:
    # 下划线转驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 主键自增
      id-type: auto

# Knife4j
knife4j:
  enable: true
  openapi:
    title: ????????API??
    description: ???????????????
    version: 1.0.0
    contact:
      name: ???
      email: developer@example.com

    group:
      default:
        api-rule: package
        api-rule-resources:
          - org.agrimachinerymanager.controller